language: java

jdk:
  - openjdk8
  

addons:
  sonarcloud:
    organization: 3aacfe8b5b095d54ca2128a4bc103641 ##Chiave generale
    token: b384f98f92ad996d016432c024cff8844433b822 ##Chiave travis


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GlaAndry_Milestone1-2